# Generated by Django 2.0.2 on 2018-03-04 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('loaned_amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('bitcoin_collateral', models.DecimalField(decimal_places=10, max_digits=20)),
                ('bitcoin_price_usd', models.DecimalField(decimal_places=10, max_digits=20)),
                ('terms_month', models.SmallIntegerField(choices=[(0, '3 Month'), (1, '6 Month'), (2, '12 Month')])),
                ('state', models.SmallIntegerField(choices=[(0, 'Submitted'), (1, 'In Review'), (2, 'Approved')])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
