# Generated by Django 2.0.2 on 2018-03-26 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_auto_20180325_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
