# Generated by Django 2.0.2 on 2018-04-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_loanapplication_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='terms_of_service_agree',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Submitted'), (1, 'In Review'), (2, 'Approved'), (3, 'Declined'), (6, 'KYC Submitted'), (7, 'KYC Verified'), (8, 'Contract Signed'), (4, 'Funded'), (5, 'Loan released')], default=0),
        ),
    ]
