# Generated by Django 2.0.2 on 2018-04-15 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('loan', '0006_auto_20180412_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='partners.Partner'),
        ),
    ]
