# Generated by Django 2.0.2 on 2018-05-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_loanapplication_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='terms_month',
            field=models.SmallIntegerField(choices=[(1, '1 Month'), (3, '3 Month'), (6, '6 Month'), (12, '12 Month')]),
        ),
    ]
