# Generated by Django 2.0.2 on 2018-04-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'BTC'), (1, 'ETH'), (2, 'LTC')])),
                ('address', models.CharField(max_length=63)),
                ('path', models.CharField(max_length=31)),
            ],
        ),
    ]
