# Generated by Django 2.0.2 on 2018-03-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171227_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('lander', 'Lander'), ('borrower', 'Borrower')], default='borrower', max_length=10),
            preserve_default=False,
        ),
    ]
