# Generated by Django 2.0.2 on 2018-04-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_applied',
            field=models.BooleanField(default=False),
        ),
    ]
