# Generated by Django 2.0.2 on 2018-05-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_kyc_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='jot_form_data',
        ),
        migrations.AddField(
            model_name='kyc',
            name='bank_info_account_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='bank_info_inst_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='bank_info_name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='bank_info_routing',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='city',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='country',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='loan_for',
            field=models.SmallIntegerField(choices=[(0, 'General Expence'), (1, 'Starting a Business'), (2, 'Purchase More Cryptocurrency'), (3, 'Debt Consolidation'), (4, 'Other')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='phone_number',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='photo_id',
            field=models.FileField(default=' ', upload_to='photo_id/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='postal_zip_code',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='proof_of_address',
            field=models.FileField(default=' ', upload_to='proof_of_address/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='selfie',
            field=models.FileField(default=' ', upload_to='selfie/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='source_of_funds',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='state_province',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='street_address',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='swift_code',
            field=models.CharField(default=' ', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='user_fullname',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
