# Generated by Django 2.0.2 on 2018-05-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180522_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kyc',
            options={'ordering': ['-added']},
        ),
    ]
