# Generated by Django 2.0.2 on 2018-02-24 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('type', models.IntegerField(choices=[(0, 'Bitcoin'), (1, 'Bitcoin Cache'), (2, 'Lite Coin')])),
                ('pub_address', models.CharField(max_length=255)),
                ('vault_id', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
