# Generated by Django 2.0.2 on 2018-03-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_auto_20180228_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinaccount',
            name='type',
            field=models.IntegerField(choices=[(0, 'Bitcoin'), (1, 'Etherium')]),
        ),
    ]
