# Generated by Django 2.0.2 on 2018-03-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinaccount',
            name='type',
            field=models.IntegerField(choices=[(0, 'Bitcoin'), (1, 'Ethereum')]),
        ),
    ]
